apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: webapp
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
