---
apiVersion: v1
kind: Pod
metadata:
  name: old-web-pod-1
  labels:
    app: old-web
spec:
  containers:
  - name: old-web-container
    image: nginx
    ports:
    - containerPort:  80
      name:  http
---
apiVersion: v1
kind: Pod
metadata:
  name: old-web-pod-2
  labels:
    app: old-web
spec:
  containers:
  - name: old-web-container
    image: nginx
    ports:
    - containerPort:  80
      name:  http
