apiVersion: v1
kind: Pod
metadata:
  name: empty-pod
spec:
  containers:
    - name: app1
      image: nginx
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html

    - name: app2
      image: nginx
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-volume
      emptyDir: {}
