---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: [ "sh", "-c", "echo 'HostPath Test' > /mnt/host/test.txt && sleep 3600" ]
      volumeMounts:
        - name: host-volume
          mountPath: /mnt/host
  volumes:
    - name: host-volume
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
