apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: [ "sh", "-c", "echo 'Testing PVC' > /mnt/pvc/test.txt && sleep 3600" ]
      volumeMounts:
        - name: pvc-storage
          mountPath: /mnt/pvc
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: pvc
