version: '3'
services:
  proxy:
    build: ./nginx
    image: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - backend
    networks:
      - proxy-network
      - shared-network
    
  backend:
    build: ./backend
    image: backend
    expose:
      - "8000"
    depends_on:
      - db
    secrets:
      - db-password
    networks:
      - backend-network
      - shared-network
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: example
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db-password
    networks:
      - db-network
      - shared-network

secrets:
  db-password:
    file: ./db_data_password/Password

volumes:
  db_data:

networks:
  proxy-network:
    driver: bridge
  backend-network:
    driver: bridge
  db-network:
    driver: bridge
  shared-network:
    driver: bridge
