apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: webapp
spec:
  selector:
    app: database
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306