apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: webapp
spec:
  selector:
    app: proxy
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30002
