#!/bin/bash

# Set the namespace
NAMESPACE="webapp"

# Create the namespace if it doesn't exist
kubectl create namespace $NAMESPACE || echo "Namespace $NAMESPACE already exists"

# Apply Persistent Volume and Persistent Volume Claim
echo "Deploying Persistent Volume and Claim..."
kubectl apply -f PV-Pvc/PV.yaml -n $NAMESPACE
kubectl apply -f PV-Pvc/PVC.yaml -n $NAMESPACE

# Apply Deployments
echo "Deploying Database..."
kubectl apply -f Deploy/Db.yaml -n $NAMESPACE

echo "Deploying Backend..."
kubectl apply -f Deploy/Backend.yaml -n $NAMESPACE

echo "Deploying Proxy..."
kubectl apply -f Deploy/Proxy.yaml -n $NAMESPACE

# Apply Services
echo "Deploying Services..."
kubectl apply -f Services/DB.yaml -n $NAMESPACE
kubectl apply -f Services/Backend.yaml -n $NAMESPACE
kubectl apply -f Services/Proxy.yaml -n $NAMESPACE

echo "Deployment completed."
