apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rc
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
     name: pod
     labels:
      app: my-app
      type: front-end
    spec:
      containers:
        - name: my-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: my-app