apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapp
  labels:
    app: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: db-password
        hostPath:
          path: ~/Orange-DevOps/Week02/Project/PV-Pvc
      containers:
      - name: backend
        image: omarbanna/backend1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: db-password
          mountPath: /run/secrets
