apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: webapp
  labels:
    app: database-deployment
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: db-password
        hostPath:
          path: ~/Orange-DevOps/Week02/Project/db-credentials
          type: File 
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - name: database
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /mnt/db-password
        - name: MYSQL_DATABASE
          value: "example"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-password
          mountPath: /mnt
        - name: db-data
          mountPath: "/var/lib/mysql"
